spring:
  # Default active profile
  application.name: exchange
  profiles.active: dev

server:
  port: 8080

---
# ----------------------------------------
# Dev
# ----------------------------------------

spring:
  profiles: dev

  datasource:
    url: jdbc:h2:file:~/exchange-WF
    driver-class-name:  org.h2.Driver
    username: sa

  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.show_sql: true

exchange:
  transaction:
    url: http://localhost:8080/v1/transactions
---
# ----------------------------------------
# Test
# ----------------------------------------

spring:
  profiles: test
  # Gives us access to the H2 database web console
  h2.console.enabled: true
  h2.console.path: /h2-console
    # Creates the database in memory
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name:  org.h2.Driver
    username: h2
    password: h2

exchange:
  transaction:
    url: http://localhost:${wiremock.server.port}/v1/transactions